### ISSUE TITLE
multiple iterations

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/collection-map#1]
This [code](https://github.com/jonschlinkert/collection-map/blob/master/index.js#L17-L19) looks like it might iterator over the object twice. Once to get the values into an array, and again to process the values with the user supplied callback function.

**Comment by jonschlinkert** [comment]
I guess the alternative would be to add a callback to get-values, so we can avoid looping twice

**Comment by doowb** [comment]
I was thinking that might be the best too, then it's the same pattern as using `arr-map`.

**Comment by phated** [comment]
Any word on this?

**Comment by jonschlinkert** [comment]
I'll take a look today

**Comment by jonschlinkert** [comment]
related https://github.com/jonschlinkert/collection-map/pull/3

**Comment by phated** [comment]
Pretty sure this was resolved by #3
