### ISSUE TITLE
1.0?

### ISSUE THREAD

**Issue by phated** [jonschlinkert/collection-map#2]
/We are looking at using this in `undertaker` - is there any chance to wrap up #1 and bump a 1.0?

**Comment by jonschlinkert** [comment]
related https://github.com/jonschlinkert/collection-map/pull/3

I also linted/updated the underlying libs and made sure they were at least 1.0

**Comment by phated** [comment]
Looks like this has been published.

**Comment by jonschlinkert** [comment]
> Looks like this has been published.

I thought I closed this in the commit, thanks!
